name: 'dbt_project'
version: '1.0.0'
config-version: 2

# La prise mâle
profile: 'etl_stocks'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_project: # <-- RECTIFIÉ : DOIT ÊTRE IDENTIQUE AU "name" EN HAUT
    staging:
      +materialized: view